# List all substances in the graph [RURAL-KG]
PREFIX sa: <http://sail.ua.edu/ruralkg/substanceabuse/>
SELECT ?substance ?name
WHERE {
  ?substance rdf:type sa:Substance .
  ?substance sa:name ?name .
}
