# List software dependencies of versions of ffmpeg [SecureChain]

PREFIX ns1: <http://example.org/ns#> .
SELECT ?package ?dependency {
  ?package ns1:isVersionOf ?software ; ns1:dependsOn ?dependency .
  FILTER(contains(str(?software),"ffmpeg"))
} order by ?package ?dependency
